# Generated by Django 3.2.8 on 2021-12-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lunchgroups', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lunchgroup',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lunchgroups.lunchgroup'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='notes',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
