# Generated by Django 3.2.8 on 2022-01-19 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_rename_lunchgroup_order_lunchgroup_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='lunchgroup_id',
            new_name='lunchgroup',
        ),
    ]
