# Generated by Django 3.2.8 on 2021-12-20 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchgroups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroup',
            name='private',
            field=models.BooleanField(default=False),
        ),
    ]
