# Generated by Django 3.2.8 on 2021-12-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchgroups', '0002_lunchgroup_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroup',
            name='invite_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
