# Generated by Django 3.2.8 on 2022-01-11 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lunchgroups', '0003_lunchgroup_invite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='lunchgroup',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
